[package]
name = "eventstore"
edition.workspace = true
version.workspace = true

[dependencies]
async-trait = { workspace = true }
eventstore = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
