[package]
name = "tracing"
edition.workspace = true
version.workspace = true

[dependencies]
tracing = { workspace = true }
tracing-appender = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "json"] }
